apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubestatsk8-app-deployment
  annotations:
    kubernetes.io/change-cause: "app deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtubestatsk8-app
  template:
    metadata:
      name: youtubestatsk8
      labels:
        app: youtubestatsk8-app
        env: prod
        app.kubernetes.io/name: youtubestatsk8-app
    spec:
      containers:
      - name: youtubestatsk8-app
        image: stkhoza/youtubeapi:latest
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10101
          name: http-web-api
   
  
---

apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: youtubestatsk8-app
  ports:
    - name:  youtubestatsk8-app-port
      port: 80
      protocol: TCP
      targetPort: 10101      
  type: LoadBalancer
